# Generated by Django 3.2.8 on 2021-10-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=4)),
                ('quantity', models.SmallIntegerField()),
                ('is_available', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.stock')),
            ],
        ),
    ]
