# Generated by Django 3.2.8 on 2021-11-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.stock'),
        ),
    ]
