# Generated by Django 3.2.8 on 2021-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20211106_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20)),
        ),
    ]
