# Generated by Django 3.2.8 on 2021-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
