# Generated by Django 3.2.8 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_stock_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='item',
            name='relevance',
            field=models.SmallIntegerField(default=0),
        ),
    ]
