# Generated by Django 3.2.8 on 2021-10-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20211022_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='showcase.item'),
        ),
    ]
