# Generated by Django 3.2.8 on 2021-10-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20211022_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='No description for now', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='goods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='showcase.goods'),
        ),
    ]
