# Generated by Django 3.2.8 on 2021-10-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20211024_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.goods'),
        ),
    ]
