# Generated by Django 3.2.8 on 2021-10-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_item_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='goods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='showcase.goods'),
        ),
    ]
