# Generated by Django 3.2.8 on 2021-10-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_item_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
