# Generated by Django 3.2.8 on 2021-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_item_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
