# Generated by Django 3.2.8 on 2021-10-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_remove_item_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
