# Generated by Django 3.2.8 on 2021-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_remove_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='/Uploads'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
