# Generated by Django 3.2.8 on 2021-10-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_auto_20211024_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='name',
        ),
    ]
